import type { CategorySlug, Product } from "./catalog-types";

/**
 * Deterministic, fictional seed catalog for Shopping Pal.
 * Every brand and product is invented; prices are integer minor units.
 */

export interface SeedProduct
  extends Omit<Product, "id" | "images" | "currency"> {
  images?: string[];
  currency?: string;
}

function p(
  slug: string,
  title: string,
  brand: string,
  category: CategorySlug,
  price: number,
  stock: number,
  ratingTenths: number,
  reviewCount: number,
  description: string,
  specs: Record<string, string>,
  tags: string[],
  featured = false,
): SeedProduct {
  return {
    slug,
    title,
    brand,
    category,
    description,
    price,
    stock,
    ratingTenths,
    reviewCount,
    tags,
    specs,
    featured,
  };
}

export const SEED_PRODUCTS: SeedProduct[] = [
  /* ── Computers ─────────────────────────────────────────────────────────── */
  p(
    "auralux-aero-14",
    "Auralux Aero 14 Ultrabook",
    "Auralux",
    "computers",
    129900,
    34,
    47,
    1834,
    "A 2.6 lb magnesium ultrabook with a 14-inch 3K OLED display, built for people who carry their office everywhere.",
    {
      CPU: "8-core Auralux A7",
      RAM: "16 GB LPDDR5",
      Storage: "512 GB NVMe SSD",
      Display: "14\" 3K OLED, 120 Hz",
      Battery: "Up to 15 hours",
      Weight: "1.18 kg",
    },
    ["laptop", "ultrabook", "portable", "work", "programming", "commuting"],
    true,
  ),
  p(
    "nordvex-studio-16",
    "Nordvex Studio 16 Creator Laptop",
    "Nordvex",
    "computers",
    189900,
    12,
    46,
    742,
    "A color-accurate creator laptop with a mini-LED panel and dedicated graphics for video and 3D work.",
    {
      CPU: "12-core Nordvex N5 Pro",
      GPU: "NV40 discrete, 8 GB",
      RAM: "32 GB DDR5",
      Storage: "1 TB NVMe SSD",
      Display: "16\" mini-LED, 100% DCI-P3",
      Battery: "Up to 10 hours",
    },
    ["laptop", "creator", "video-editing", "design"],
  ),
  p(
    "kite-systems-k1-mini-pc",
    "Kite Systems K1 Mini PC",
    "Kite Systems",
    "computers",
    54900,
    41,
    44,
    389,
    "A palm-sized desktop that drives two 4K displays, quiet enough for a bedroom desk setup.",
    {
      CPU: "8-core Kite KX3",
      RAM: "16 GB DDR5 (upgradable)",
      Storage: "512 GB NVMe SSD",
      Ports: "2x HDMI 2.1, 4x USB, 2.5 GbE",
      Noise: "22 dB idle",
    },
    ["desktop", "mini-pc", "home-office", "programming"],
  ),
  p(
    "helioform-airbook-13",
    "Helioform AirBook 13",
    "Helioform",
    "computers",
    69900,
    58,
    43,
    1267,
    "A dependable everyday laptop for classes, browsing, and documents — with all-day battery.",
    {
      CPU: "6-core Helioform H2",
      RAM: "8 GB LPDDR4x",
      Storage: "256 GB NVMe SSD",
      Display: "13.3\" IPS 1080p",
      Battery: "Up to 13 hours",
      Weight: "1.25 kg",
    },
    ["laptop", "student", "budget", "everyday"],
  ),
  p(
    "quill-byte-scribe-pro",
    "Quill & Byte Scribe Pro",
    "Quill & Byte",
    "computers",
    219900,
    8,
    48,
    512,
    "A developer workstation with a 32 GB RAM ceiling, excellent keyboard, and Linux-friendly firmware.",
    {
      CPU: "12-core Quill Q9",
      RAM: "32 GB DDR5",
      Storage: "2 TB NVMe SSD",
      Display: "14\" 2.8K matte IPS",
      Battery: "Up to 12 hours",
      Keyboard: "1.5 mm travel, hot-swap?",
    },
    ["laptop", "programming", "workstation", "developer"],
  ),
  p(
    "nordvex-flux-14-gaming",
    "Nordvex Flux 14 Gaming Laptop",
    "Nordvex",
    "computers",
    149900,
    0,
    45,
    663,
    "A 14-inch gaming machine with a vapor chamber that keeps clocks high without jet-engine fans.",
    {
      CPU: "8-core Nordvex N5",
      GPU: "NV35 discrete, 6 GB",
      RAM: "16 GB DDR5",
      Storage: "1 TB NVMe SSD",
      Display: "14\" IPS 165 Hz",
    },
    ["laptop", "gaming"],
  ),
  p(
    "kite-systems-tab-s11",
    "Kite Systems Tab S11 Tablet",
    "Kite Systems",
    "computers",
    47900,
    27,
    45,
    908,
    "An 11-inch tablet with laminated glass and stylus support that doubles as a second travel screen.",
    {
      Display: "11\" LTPS 2400x1600",
      Storage: "128 GB",
      Stylus: "Supported (sold separately)",
      Battery: "Up to 12 hours",
      Weight: "480 g",
    },
    ["tablet", "reading", "travel", "students"],
  ),
  p(
    "quill-byte-devdesk-tower",
    "Quill & Byte DevDesk Tower",
    "Quill & Byte",
    "computers",
    99900,
    15,
    47,
    287,
    "A tool-less micro-ATX tower with workstation silicon and room to grow to 128 GB of RAM.",
    {
      CPU: "10-core Quill Q7",
      RAM: "32 GB DDR5 ECC",
      Storage: "1 TB NVMe + 2 TB HDD",
      PSU: "650 W 80+ Gold",
      Expansion: "mATX, 4 slots",
    },
    ["desktop", "tower", "programming", "workstation"],
  ),
  p(
    "auralux-chromenote-go",
    "Auralux ChromeNote Go",
    "Auralux",
    "computers",
    32900,
    63,
    42,
    1543,
    "A fanless cloud laptop that boots in seconds — the grab-and-go machine for the kitchen counter.",
    {
      CPU: "6-core Auralux A5",
      RAM: "8 GB",
      Storage: "128 GB eMMC",
      Display: "13.3\" IPS touch",
      Weight: "1.1 kg",
    },
    ["laptop", "budget", "lightweight", "student"],
  ),

  /* ── Computer accessories ─────────────────────────────────────────────── */
  p(
    "helioform-terra-27-monitor",
    "Helioform Terra 27\" 4K Monitor",
    "Helioform",
    "computer-accessories",
    44900,
    52,
    46,
    1120,
    "A 27-inch 4K IPS monitor with factory calibration and a single-cable USB-C dock inside.",
    {
      Panel: "27\" IPS 4K, 60 Hz",
      Color: "99% sRGB, Delta-E < 2",
      Hub: "USB-C 90 W PD + ethernet",
      Stand: "Height/tilt/pivot adjustable",
    },
    ["monitor", "4k", "usb-c", "programming", "desk-setup"],
    true,
  ),
  p(
    "helioform-vista-34-ultrawide",
    "Helioform Vista 34\" Ultrawide",
    "Helioform",
    "computer-accessories",
    79900,
    19,
    45,
    405,
    "A 34-inch 144 Hz ultrawide that replaces a dual-monitor armful with one clean curve.",
    {
      Panel: "34\" VA curved, 3440x1440",
      Refresh: "144 Hz",
      Sync: "Adaptive sync",
      Inputs: "DisplayPort 1.4, 2x HDMI",
    },
    ["monitor", "ultrawide", "gaming", "productivity"],
  ),
  p(
    "deskline-rise-converter",
    "Deskline Rise Standing Desk Converter",
    "Deskline",
    "computer-accessories",
    18900,
    33,
    44,
    655,
    "Gas-spring riser that turns any desk into a sit-stand station in three seconds.",
    {
      Surface: "31.5\" x 16\"",
      HeightRange: "4.7\" – 19.7\"",
      Capacity: "33 lbs",
      Assembly: "Arrives assembled",
    },
    ["standing-desk", "ergonomics", "office", "desk-setup"],
  ),
  p(
    "deskline-float-arm",
    "Deskline Float Monitor Arm",
    "Deskline",
    "computer-accessories",
    7900,
    88,
    46,
    1980,
    "Full-motion aluminum monitor arm that clears desk space and hides your cables.",
    {
      Fits: '17"–34" flat panels',
      Capacity: "19.8 lbs",
      Motion: "Tilt ±90°, swivel 180°",
      Mount: "C-clamp or grommet",
    },
    ["monitor-arm", "desk-setup", "ergonomics"],
  ),
  p(
    "vantage-labs-mech-75-keyboard",
    "Vantage Labs Mech 75 Keyboard",
    "Vantage Labs",
    "computer-accessories",
    14900,
    46,
    47,
    2311,
    "A gasket-mounted 75% mechanical keyboard with hot-swap sockets and a satisfying thock.",
    {
      Layout: "75% (82 keys)",
      Switches: "Hot-swappable linear, pre-lubed",
      Connection: "USB-C / Bluetooth / 2.4 GHz",
      Battery: "4000 mAh",
      Keycaps: "PBT double-shot",
    },
    ["keyboard", "mechanical", "programming", "desk-setup"],
    true,
  ),
  p(
    "vantage-labs-type-zero-keyboard",
    "Vantage Labs Type Zero Low-Profile",
    "Vantage Labs",
    "computer-accessories",
    11900,
    39,
    44,
    764,
    "Laptop-style key feel on a full aluminum deck, quiet enough for shared offices.",
    {
      Profile: "Low-profile scissor-switch",
      Connection: "Bluetooth, 3 devices",
      Battery: "Up to 90 days",
      Layout: "Full-size with numpad",
    },
    ["keyboard", "quiet", "office", "bluetooth"],
  ),
  p(
    "grid-grain-precision-mouse",
    "Grid & Grain Precision Mouse",
    "Grid & Grain",
    "computer-accessories",
    8900,
    71,
    45,
    1502,
    "A sculpted ergonomic mouse with silent clicks and a free-spinning scroll wheel.",
    {
      Sensor: "8000 DPI optical",
      Buttons: "6 programmable",
      Battery: "70 days per charge",
      Connection: "USB-C dongle or Bluetooth",
    },
    ["mouse", "ergonomic", "quiet", "office"],
  ),
  p(
    "tessel-dock-8-in-1-hub",
    "Tessel Dock 8-in-1 USB-C Hub",
    "Tessel",
    "computer-accessories",
    5900,
    94,
    43,
    877,
    "One hub to rule the café table: dual 4K HDMI, gigabit ethernet, SD, and 100 W passthrough.",
    {
      Ports: "2x HDMI, USB-A x3, USB-C PD, SD/microSD, RJ45",
      Passthrough: "Up to 100 W",
      Body: "Braided cable, aluminum shell",
    },
    ["hub", "usb-c", "travel", "laptop"],
  ),
  p(
    "lumenark-halo-webcam",
    "Lumenark Halo 4K Webcam",
    "Lumenark",
    "computer-accessories",
    12900,
    44,
    45,
    596,
    "A Sony-sensor webcam with on-device framing that keeps you centered without subscription software.",
    {
      Resolution: "4K30 / 1080p60",
      FieldOfView: "78° with privacy shutter",
      Mic: "Dual noise-canceling",
      Mount: "Monitor clip + tripod thread",
    },
    ["webcam", "video-calls", "wfh"],
  ),
  p(
    "fieldnote-drive-2tb-ssd",
    "Fieldnote Drive 2 TB Portable SSD",
    "Fieldnote",
    "computer-accessories",
    15900,
    57,
    46,
    1345,
    "A pocketable IP55 SSD that reads at 1050 MB/s and survives being sat on.",
    {
      Capacity: "2 TB",
      Speed: "1050 MB/s read, 1000 MB/s write",
      Durability: "IP55, 2 m drop",
      Encryption: "AES 256-bit hardware",
    },
    ["ssd", "storage", "backup", "travel"],
  ),

  /* ── Audio ─────────────────────────────────────────────────────────────── */
  p(
    "marlowe-pulse-anc-headphones",
    "Marlowe Sound Pulse ANC Headphones",
    "Marlowe Sound",
    "audio",
    19900,
    61,
    47,
    3208,
    "Over-ear noise cancelers with a warm, forgiving sound and 40-hour battery — commute armor.",
    {
      Type: "Over-ear, closed back",
      ANC: "Hybrid adaptive ANC",
      Battery: "40 h (ANC on), USB-C fast charge",
      Weight: "265 g",
      Multipoint: "Two devices",
    },
    ["headphones", "anc", "commuting", "travel", "noise-cancelling"],
    true,
  ),
  p(
    "northwind-fjord-anc-headphones",
    "Northwind Acoustics Fjord ANC",
    "Northwind Acoustics",
    "audio",
    24900,
    24,
    48,
    1877,
    "Reference-leaning tuning with class-leading silence — the pick if music matters more than bass.",
    {
      Type: "Over-ear, closed back",
      ANC: "Dual-chip adaptive ANC",
      Battery: "45 h (ANC on)",
      Codec: "LDAC, AAC, SBC",
      Weight: "272 g",
    },
    ["headphones", "anc", "commuting", "audiophile", "travel", "noise-cancelling"],
  ),
  p(
    "tidepool-sprint-2-earbuds",
    "Tidepool Audio Sprint 2 Earbuds",
    "Tidepool Audio",
    "audio",
    8900,
    120,
    46,
    5210,
    "Sweatproof sport earbuds with wing tips that refuse to fall out mid-interval.",
    {
      Type: "True wireless in-ear",
      WaterResistance: "IPX7 (buds and case)",
      Battery: "8 h buds, 28 h case",
      Fit: "Wing-tip sport fins",
      Codec: "AAC, SBC",
    },
    ["earbuds", "gym", "running", "waterproof", "workout"],
    true,
  ),
  p(
    "marlowe-studio-one-headphones",
    "Marlowe Sound Studio One Wired",
    "Marlowe Sound",
    "audio",
    12900,
    37,
    46,
    942,
    "Flat-response wired monitors for mixing — no battery, no latency, no coloration.",
    {
      Type: "Over-ear, closed back",
      Response: "10 Hz – 30 kHz",
      Impedance: "38 ohms",
      Cable: "Detachable 2 m, 3.5 mm",
      Weight: "294 g",
    },
    ["headphones", "studio", "mixing", "wired", "music-production"],
  ),
  p(
    "tidepool-drift-open-ear-buds",
    "Tidepool Audio Drift Open-Ear",
    "Tidepool Audio",
    "audio",
    10900,
    48,
    44,
    1108,
    "Open-ear air-conduction buds that keep you aware of traffic while you run.",
    {
      Type: "Open-ear clip design",
      Battery: "7 h buds, 24 h case",
      WaterResistance: "IPX7",
      Safety: "Ambient awareness by design",
    },
    ["earbuds", "running", "cycling", "open-ear", "safety"],
  ),
  p(
    "hushwave-quiet-mini-earbuds",
    "Hushwave Quiet Mini Earbuds",
    "Hushwave",
    "audio",
    6900,
    132,
    43,
    3402,
    "Tiny ANC earbuds at an unreasonably friendly price — great first pair or gym spare.",
    {
      Type: "True wireless in-ear",
      ANC: "Active noise cancellation",
      Battery: "6 h buds, 22 h case",
      WeightPerBud: "4.1 g",
    },
    ["earbuds", "anc", "budget", "gym", "commuting"],
  ),
  p(
    "northwind-bloom-speakers",
    "Northwind Acoustics Bloom Desktop Speakers",
    "Northwind Acoustics",
    "audio",
    22900,
    17,
    47,
    388,
    "Powered bookshelf speakers with real wood veneer and a soundstage twice their size.",
    {
      Power: "50 W RMS per speaker",
      Inputs: "USB-C DAC, RCA, 3.5 mm, optical",
      Driver: '4" woofer + silk tweeter',
      Finish: "Walnut veneer",
    },
    ["speakers", "desktop", "audiophile", "music"],
  ),
  p(
    "cadence-wave-portable-speaker",
    "Cadence Wave Portable Speaker",
    "Cadence Wave",
    "audio",
    13900,
    55,
    45,
    1622,
    "A 360-degree speaker with enough low end for a park picnic and IP67 for the beach.",
    {
      Output: "30 W, 360° array",
      Battery: "20 hours",
      WaterResistance: "IP67",
      Pairing: "Stereo pair up to 8 units",
    },
    ["speaker", "bluetooth", "party", "outdoors", "beach"],
  ),
  p(
    "cadence-wave-mini-speaker",
    "Cadence Wave Mini Speaker",
    "Cadence Wave",
    "audio",
    5900,
    143,
    43,
    2450,
    "Palm-sized speaker with a strap for handlebars, showers, and stroller pushes.",
    {
      Output: "8 W",
      Battery: "14 hours",
      WaterResistance: "IP67",
      Strap: "Integrated silicone loop",
    },
    ["speaker", "bluetooth", "budget", "shower", "bike"],
  ),
  p(
    "marlowe-cadence-usb-microphone",
    "Marlowe Sound Cadence USB Microphone",
    "Marlowe Sound",
    "audio",
    9900,
    49,
    46,
    733,
    "Cardioid USB-C condenser that makes closet recordings sound treated.",
    {
      Capsule: "14 mm cardioid condenser",
      SampleRate: "24-bit / 96 kHz",
      Monitoring: "Zero-latency headphone jack",
      Mount: "Desk tripod included",
    },
    ["microphone", "podcast", "streaming", "recording"],
  ),

  /* ── Phones & accessories ─────────────────────────────────────────────── */
  p(
    "voltra-volt-20k-power-bank",
    "Voltra Volt 20K Power Bank",
    "Voltra",
    "phones-accessories",
    4900,
    102,
    46,
    2890,
    "A 20,000 mAh bank that charges a laptop and still has juice for the flight home.",
    {
      Capacity: "20,000 mAh / 74 Wh",
      Output: "65 W USB-C PD + 18 W USB-A",
      Recharge: "0–80% in 90 min",
      Display: "% remaining readout",
    },
    ["power-bank", "charger", "travel", "laptop", "commuting"],
    true,
  ),
  p(
    "voltra-nano-5k-power-bank",
    "Voltra Nano 5K Power Bank",
    "Voltra",
    "phones-accessories",
    2500,
    210,
    44,
    1760,
    "Credit-card sized emergency charger with an integrated USB-C plug — no cable needed.",
    {
      Capacity: "5,000 mAh",
      Output: "20 W USB-C direct plug",
      Weight: "98 g",
      AirlineSafe: "Yes",
    },
    ["power-bank", "pocket", "emergency", "budget"],
  ),
  p(
    "beamline-65w-gan-charger",
    "Beamline 65 W GaN Charger",
    "Beamline",
    "phones-accessories",
    3900,
    156,
    47,
    2140,
    "One foldable-plug brick that replaces the chargers for your phone, tablet, and laptop.",
    {
      Output: "65 W total (PD 3.0 / PPS)",
      Ports: "2x USB-C, 1x USB-A",
      Size: "Folding prongs, 52% smaller than stock",
    },
    ["charger", "gan", "travel", "usb-c"],
  ),
  p(
    "beamline-trio-charging-dock",
    "Beamline Trio Charging Dock",
    "Beamline",
    "phones-accessories",
    8900,
    64,
    44,
    980,
    "A weighted three-device stand that ends the nightly cable hunt on your nightstand.",
    {
      Charges: "Phone + watch + earbuds",
      Output: "15 W magnetic phone pad",
      Material: "Aluminum + vegan leather",
    },
    ["charging-dock", "nightstand", "wireless-charging", "desk-setup"],
  ),
  p(
    "casecraft-clearshield-case",
    "Casecraft ClearShield Phone Case",
    "Casecraft",
    "phones-accessories",
    2900,
    178,
    45,
    3120,
    "Anti-yellowing clear case with raised bezels and real drop protection.",
    {
      Protection: "MIL-STD 810G, 3 m drops",
      Material: "Optically clear TPU + PC",
      MagSafeCompatible: "Yes",
    },
    ["case", "clear", "protective", "phone"],
  ),
  p(
    "casecraft-rugged-armor-case",
    "Casecraft Rugged Armor Case",
    "Casecraft",
    "phones-accessories",
    3500,
    121,
    46,
    1877,
    "Grippy armored bumper with a lanyard slot for people who drop phones for a living.",
    {
      Protection: "4 m drop rated",
      Grip: "Textured TPE perimeter",
      Extras: "Lanyard slot, button covers",
    },
    ["case", "rugged", "protective", "work"],
  ),
  p(
    "casecraft-glass-screen-protector",
    "Casecraft Glass Screen Protector (2-pack)",
    "Casecraft",
    "phones-accessories",
    1500,
    260,
    44,
    4310,
    "Case-friendly tempered glass with an alignment frame — bubble-free in ninety seconds.",
    {
      Hardness: "9H tempered glass",
      Oleophobic: "Yes",
      Includes: "2 protectors, dust-free install frame",
    },
    ["screen-protector", "glass", "phone"],
  ),
  p(
    "beamline-magnetic-car-mount",
    "Beamline Magnetic Car Mount",
    "Beamline",
    "phones-accessories",
    3200,
    87,
    43,
    1240,
    "Strong-magnet vent mount that survives potholes and one-handed docking.",
    {
      Hold: "N52 magnet array",
      MountType: "Vent clip, ball joint",
      CableRouting: "Back channel for charging cable",
    },
    ["car-mount", "magnetic", "driving"],
  ),
  p(
    "voltra-braided-usbc-cable-2m",
    "Voltra Braided USB-C Cable (2 m)",
    "Voltra",
    "phones-accessories",
    1400,
    300,
    46,
    5200,
    "240 W-rated e-marked cable with a lifetime warranty and zero fray after a year in a backpack.",
    {
      Rating: "240 W / 40 Gbps e-marked",
      Length: "2 m braided nylon",
      Warranty: "Lifetime replacement",
    },
    ["cable", "usb-c", "charging", "durable"],
  ),

  /* ── Fitness ───────────────────────────────────────────────────────────── */
  p(
    "ironvale-adjustable-dumbbells",
    "Ironvale Adjustable Dumbbells (Pair)",
    "Ironvale",
    "fitness",
    34900,
    21,
    47,
    1456,
    "Five dumbbells' worth of iron in one dial — 5 to 52.5 lb per hand, swapped in two seconds.",
    {
      WeightRange: "5–52.5 lb per dumbbell",
      Increments: "2.5 lb up to 25 lb",
      Mechanism: "Dial selector lock",
      Included: "Storage trays",
    },
    ["strength-training", "home-gym", "dumbbells", "weights"],
    true,
  ),
  p(
    "ironvale-cast-iron-kettlebell",
    "Ironvale Cast-Iron Kettlebell 35 lb",
    "Ironvale",
    "fitness",
    7900,
    44,
    46,
    892,
    "Single-cast iron with a powder-coat grip that chalk loves — swings, goblets, carries.",
    {
      Weight: "35 lb (16 kg)",
      Finish: "Powder-coated matte",
      Handle: "35 mm, wide enough for two hands",
      Base: "Flat, rubber-free",
    },
    ["kettlebell", "strength-training", "home-gym"],
  ),
  p(
    "summit-forge-weight-bench",
    "Summit Forge Foldable Weight Bench",
    "Summit Forge",
    "fitness",
    18900,
    26,
    45,
    611,
    "Seven-position bench that folds under a bed yet holds 600 lb of you plus iron.",
    {
      Positions: "7 back angles",
      Capacity: "600 lb",
      Folded: "Folds flat, 13\" tall",
      Pad: "High-density foam, sweat-proof vinyl",
    },
    ["bench", "home-gym", "strength-training", "foldable"],
  ),
  p(
    "pacekeeper-runband-gps-watch",
    "Pacekeeper RunBand GPS Watch",
    "Pacekeeper",
    "fitness",
    17900,
    38,
    46,
    1233,
    "Multiband GPS running watch with training load guidance and 26-hour battery in GPS mode.",
    {
      GPS: "Multiband, 5 satellites",
      Battery: "26 h GPS / 12 days smartwatch",
      Metrics: "VO2 est., training load, recovery",
      WaterRating: "5 ATM",
    },
    ["gps-watch", "running", "training", "triathlon"],
  ),
  p(
    "pacekeeper-pulse-tracker",
    "Pacekeeper Pulse Fitness Tracker",
    "Pacekeeper",
    "fitness",
    8900,
    92,
    44,
    2760,
    "Slim daily tracker that nails sleep staging and quietly nudges you toward steps goals.",
    {
      Sensors: "Heart rate, SpO2, skin temp",
      Battery: "10 days",
      Sleep: "Automatic sleep staging",
      WaterRating: "5 ATM",
    },
    ["tracker", "sleep", "steps", "health", "budget"],
  ),
  p(
    "kinetic-labs-resistance-band-set",
    "Kinetic Labs Resistance Band Set",
    "Kinetic Labs",
    "fitness",
    3900,
    130,
    45,
    1985,
    "Five stackable latex bands, door anchor, and handles — a whole gym in a shoe pouch.",
    {
      Resistance: "5 bands, 10–50 lb each",
      StackableTo: "150 lb",
      Includes: "Door anchor, ankle straps, handles, pouch",
    },
    ["resistance-bands", "home-gym", "travel-workout", "budget"],
  ),
  p(
    "kinetic-labs-yoga-mat-pro",
    "Kinetic Labs Yoga Mat Pro",
    "Kinetic Labs",
    "fitness",
    5800,
    76,
    47,
    1650,
    "Natural rubber mat with an alignment grid that grips harder as you sweat.",
    {
      Material: "Natural rubber, polyurethane top",
      Thickness: "5 mm",
      Dimensions: "72\" x 26\"",
      Grip: "Wet-grip surface",
    },
    ["yoga", "mat", "pilates", "stretching"],
  ),
  p(
    "summit-forge-half-rack",
    "Summit Forge Half Rack",
    "Summit Forge",
    "fitness",
    49900,
    9,
    48,
    287,
    "11-gauge steel half rack with integrated pull-up bar — garage-gym centerpiece.",
    {
      Steel: "11-gauge, 3x3\" uprights",
      HoleSpacing: "Westside spacing (1\")",
      PullUpBar: "Multi-grip included",
      Capacity: "1000 lb",
    },
    ["rack", "power-rack", "home-gym", "barbell"],
  ),
  p(
    "ironvale-weighted-jump-rope",
    "Ironvale Weighted Jump Rope",
    "Ironvale",
    "fitness",
    1900,
    180,
    45,
    2210,
    "Ball-bearing speed rope with removable 0.5 lb handles for cardio that counts double.",
    {
      HandleWeight: "0.25 lb each, removable",
      Cable: 'Adjustable 9"–10\' steel',
      Bearings: "Dual ball-bearing swivel",
    },
    ["jump-rope", "cardio", "crossfit", "travel-workout"],
  ),
  p(
    "kinetic-labs-textured-foam-roller",
    "Kinetic Labs Textured Foam Roller",
    "Kinetic Labs",
    "fitness",
    2800,
    115,
    44,
    1390,
    "Medium-density roller with a texture map that finds knots without bruising bone.",
    {
      Density: "Medium (beginner friendly)",
      Surface: "EVA texture zones",
      Size: "13\" x 5\"",
    },
    ["recovery", "foam-roller", "mobility"],
  ),

  /* ── Home ──────────────────────────────────────────────────────────────── */
  p(
    "fernway-cloudweave-blanket",
    "Fernway Home Cloudweave Weighted Blanket 15 lb",
    "Fernway Home",
    "home",
    6900,
    68,
    46,
    2410,
    "Glass-bead weighted blanket with a bamboo cover that stays cool for hot sleepers.",
    {
      Weight: "15 lb (fits queen)",
      Cover: "Removable bamboo viscose",
      Fill: "Micro glass beads",
      Care: "Machine-washable cover",
    },
    ["blanket", "sleep", "cozy", "anxiety-relief"],
  ),
  p(
    "fernway-linen-duvet-cover",
    "Fernway Home Linen Duvet Cover — Queen",
    "Fernway Home",
    "home",
    12900,
    42,
    47,
    1130,
    "Stonewashed European flax that gets softer every wash and breathes year-round.",
    {
      Material: "100% European flax linen",
      Weave: "Stonewashed 165 GSM",
      Closure: "Coconut buttons",
      Care: "Machine wash cold",
    },
    ["bedding", "linen", "duvet", "queen"],
  ),
  p(
    "oaklight-aura-floor-lamp",
    "Oaklight Aura Floor Lamp",
    "Oaklight",
    "home",
    9800,
    36,
    45,
    720,
    "An arched brass floor lamp that throws warm light exactly where the reading chair is.",
    {
      Height: "68\" arch",
      Bulb: "E26 LED included (2700 K)",
      Dimmable: "Foot dimmer switch",
      Finish: "Brushed brass, marble base",
    },
    ["lamp", "lighting", "living-room", "reading"],
  ),
  p(
    "oaklight-ember-smart-bulbs",
    "Oaklight Ember Smart Bulbs (4-pack)",
    "Oaklight",
    "home",
    4400,
    95,
    44,
    1866,
    "Warm-to-cool white and scene colors, scheduled locally so they work even offline.",
    {
      WhiteRange: "2200–5000 K",
      Colors: "16 million",
      Protocol: "Wi-Fi + local control",
      Lifespan: "25,000 hours",
    },
    ["smart-home", "bulbs", "lighting"],
  ),
  p(
    "oaklight-breeze-hepa-purifier",
    "Oaklight Breeze HEPA Purifier",
    "Oaklight",
    "home",
    15900,
    31,
    46,
    1044,
    "Quiet true-HEPA purifier sized for bedrooms — sleeps quieter than the cat.",
    {
      Coverage: "Up to 550 sq ft",
      Filter: "True HEPA H13 + carbon",
      Noise: "22 dB sleep mode",
      CADR: "250 m³/h",
    },
    ["air-purifier", "allergy", "bedroom", "hepa"],
  ),
  p(
    "dovetail-desk-organizer",
    "Dovetail Living Walnut Desk Organizer",
    "Dovetail Living",
    "home",
    5400,
    54,
    46,
    512,
    "Solid walnut catch-all with a felt-lined tray that makes any desk look intentional.",
    {
      Material: "Solid American walnut",
      Compartments: "Pen well, phone slot, valet tray",
      Base: "Non-slip felt",
    },
    ["desk-organizer", "walnut", "office", "gift"],
  ),
  p(
    "dovetail-wool-area-rug",
    "Dovetail Living Wool Area Rug 5x8",
    "Dovetail Living",
    "home",
    24000,
    14,
    45,
    333,
    "Hand-tufted New Zealand wool in a heathered herringbone that hides real life.",
    {
      Material: "100% NZ wool",
      Size: "5' x 8'",
      Pile: "Low, hand-tufted",
      Backing: "Cotton, rug-pad recommended",
    },
    ["rug", "wool", "living-room"],
  ),
  p(
    "fernway-blackout-curtains",
    "Fernway Home Blackout Curtains (Pair)",
    "Fernway Home",
    "home",
    5900,
    73,
    44,
    1580,
    "Triple-weave curtains that genuinely black out noon light and trim summer heat.",
    {
      Blackout: "99% light blocking",
      Size: "52\" x 84\" per panel",
      Thermal: "Triple-weave insulating layer",
      Hanging: "Back tabs or rod pocket",
    },
    ["curtains", "blackout", "sleep", "energy-saving"],
  ),
  p(
    "oaklight-arc-table-lamp",
    "Oaklight Arc Table Lamp",
    "Oaklight",
    "home",
    7200,
    40,
    44,
    466,
    "Ceramic arc lamp with a linen shade — soft evening light for consoles and nightstands.",
    {
      Height: "21\"",
      Bulb: "E12 LED included",
      Dimmer: "Inline rotary",
      Shade: "Natural linen drum",
    },
    ["lamp", "table-lamp", "bedroom", "lighting"],
  ),
  p(
    "dovetail-ceramic-diffuser",
    "Dovetail Living Ceramic Diffuser",
    "Dovetail Living",
    "home",
    3800,
    82,
    43,
    690,
    "Ultrasonic stone-look diffuser with a whisper mode and eight-hour timer.",
    {
      TankSize: "300 ml",
      Runtime: "Up to 8 h",
      Modes: "Intermittent mist, 7-color light off/on",
    },
    ["diffuser", "aromatherapy", "gift"],
  ),

  /* ── Kitchen ───────────────────────────────────────────────────────────── */
  p(
    "copperline-10pc-cookware-set",
    "Copperline 10-Piece Cookware Set",
    "Copperline Kitchen",
    "kitchen",
    24900,
    23,
    47,
    1420,
    "Tri-ply stainless set with stay-cool handles — induction-ready and dishwasher-indifferent.",
    {
      Pieces: "10 (3 pans, 3 pots, lids)",
      Build: "Tri-ply, aluminum core",
      Compatible: "Induction, oven-safe to 600°F",
      Handles: "Riveted stay-cool",
    },
    ["cookware", "stainless", "induction", "wedding-gift"],
    true,
  ),
  p(
    "copperline-cast-iron-skillet",
    "Copperline Cast-Iron Skillet 12\"",
    "Copperline Kitchen",
    "kitchen",
    4900,
    88,
    47,
    3105,
    "Pre-seasoned skillet with machined cooking surface — cornbread to steaks to frittatas.",
    {
      Diameter: "12\"",
      Weight: "8 lb",
      PreSeasoned: "Yes, flaxseed oil",
      OvenSafe: "Any temperature",
    },
    ["skillet", "cast-iron", "searing", "camping"],
  ),
  p(
    "mise-main-chef-knife",
    "Mise & Main Chef Knife 8\"",
    "Mise & Main",
    "kitchen",
    11900,
    47,
    48,
    1670,
    "Damascus-clad VG-10 blade balanced at the bolster — the knife that upgrades every meal.",
    {
      Blade: '8" VG-10 core, 33-layer Damascus',
      Hardness: "60±2 HRC",
      Handle: "Stabilized pakkawood",
      Balance: "Bolster-forward pinch grip",
    },
    ["knife", "chef-knife", "cooking", "gift"],
  ),
  p(
    "mise-main-bamboo-cutting-board",
    "Mise & Main XL Bamboo Cutting Board",
    "Mise & Main",
    "kitchen",
    3600,
    96,
    45,
    2040,
    "End-grain bamboo board big enough to break down a chicken with elbow room left over.",
    {
      Size: "18\" x 12\" x 1\"",
      Material: "End-grain organic bamboo",
      Extras: "Juice groove, side handles",
    },
    ["cutting-board", "bamboo", "prep"],
  ),
  p(
    "stoneware-gooseneck-kettle",
    "Stoneware Co. Gooseneck Pour-Over Kettle",
    "Stoneware Co.",
    "kitchen",
    4200,
    79,
    46,
    1810,
    "Electric gooseneck with ±1° temperature hold — bloom like you mean it.",
    {
      Capacity: "0.8 L",
      TempControl: "Set 104–212°F, 60-min hold",
      Flow: "Precision gooseneck spout",
      Body: "Matte stainless",
    },
    ["coffee", "pour-over", "kettle", "tea"],
  ),
  p(
    "stoneware-burr-grinder",
    "Stoneware Co. Conical Burr Grinder",
    "Stoneware Co.",
    "kitchen",
    8900,
    51,
    46,
    1330,
    "40-step conical burr grinder quiet enough for 6 a.m. espresso without apologies.",
    {
      Burrs: "40 mm hardened conical",
      GrindSteps: "40 stepped settings",
      Hopper: "8 oz with anti-static grounds cup",
      Noise: "< 72 dB",
    },
    ["coffee", "grinder", "espresso", "beans"],
  ),
  p(
    "mise-main-dutch-oven",
    "Mise & Main Enameled Dutch Oven 5 qt",
    "Mise & Main",
    "kitchen",
    13500,
    34,
    47,
    2255,
    "Heavy enameled cast iron that sears, bakes sourdough, and looks good doing it.",
    {
      Capacity: "5 qt",
      Material: "Enameled cast iron",
      Lid: "Self-basting interior spikes",
      OvenSafe: "To 500°F",
    },
    ["dutch-oven", "bread", "braising", "cooking"],
  ),
  p(
    "stoneware-digital-scale",
    "Stoneware Co. Digital Kitchen Scale",
    "Stoneware Co.",
    "kitchen",
    2200,
    140,
    45,
    2870,
    "0.1 g resolution scale with a timer for espresso — bakes and shots both land on target.",
    {
      Resolution: "0.1 g to 3 kg",
      Timer: "Built-in brew timer",
      Units: "g / oz / lb",
      Power: "USB-C rechargeable",
    },
    ["scale", "baking", "coffee", "precision"],
  ),
  p(
    "copperline-electric-kettle",
    "Copperline Electric Kettle 1.7 L",
    "Copperline Kitchen",
    "kitchen",
    3800,
    101,
    44,
    1990,
    "Fast-boiling stainless kettle with a British accent and a reliable auto-shutoff.",
    {
      Capacity: "1.7 L / 7 cups",
      BoilTime: "About 4 min full",
      Safety: "Boil-dry protection",
      Body: "Brushed stainless",
    },
    ["kettle", "tea", "fast-boil"],
  ),
  p(
    "mise-main-sharpening-rod",
    "Mise & Main Honing Rod",
    "Mise & Main",
    "kitchen",
    2400,
    118,
    45,
    940,
    "Fine ceramic honing rod that realigns edges in four passes, no oil required.",
    {
      Rod: '10" fine ceramic',
      Handle: "Contoured beech",
      UseCase: "Weekly edge maintenance",
    },
    ["knife-care", "honing", "sharpener"],
  ),

  /* ── Outdoors ──────────────────────────────────────────────────────────── */
  p(
    "ridgeline-summit-45-backpack",
    "Ridgeline Summit 45 L Backpack",
    "Ridgeline Outfitters",
    "outdoors",
    16900,
    29,
    47,
    1122,
    "Weekend-capable pack with a real hip belt and a suspension that moves weight to your hips.",
    {
      Capacity: "45 L",
      Frame: "Internal frame, load transfer",
      HipBelt: "Padded, pocketed",
      RainCover: "Included",
      Weight: "1.6 kg",
    },
    ["backpack", "hiking", "camping", "weekend-trip"],
    true,
  ),
  p(
    "ridgeline-cloudrest-sleeping-bag",
    "Ridgeline Cloudrest Sleeping Bag 20°F",
    "Ridgeline Outfitters",
    "outdoors",
    12900,
    33,
    45,
    870,
    "Three-season synthetic bag that shrugs off damp mornings and packs to camp-chair size.",
    {
      Rating: "20°F comfort",
      Fill: "Synthetic (packs wet)",
      Packed: "16\" x 8\" compression sack",
      Shell: "Ripstop polyester DWR",
    },
    ["sleeping-bag", "camping", "three-season"],
  ),
  p(
    "trailhead-basecamp-2p-tent",
    "Trailhead Supply Basecamp 2P Tent",
    "Trailhead Supply",
    "outdoors",
    19900,
    22,
    46,
    905,
    "Freestanding two-person tent with twin doors and a vestibule each — no climbing over anyone.",
    {
      Capacity: "2 person",
      Weight: "4.4 lb packed",
      Doors: "2 doors + 2 vestibules",
      Poles: "DAC-style aluminum",
    },
    ["tent", "camping", "backpacking", "two-person"],
  ),
  p(
    "trailhead-trekking-poles",
    "Trailhead Supply Trekking Poles (Pair)",
    "Trailhead Supply",
    "outdoors",
    6400,
    58,
    46,
    1310,
    "Aluminum flip-lock poles with cork grips that save knees on the way down.",
    {
      Material: "7075 aluminum",
      Locks: "Flip-lock lever",
      Grips: "Extended EVA cork",
      Range: "100–135 cm",
    },
    ["trekking-poles", "hiking", "knee-support"],
  ),
  p(
    "cascade-insulated-bottle-32oz",
    "Cascade Gear Insulated Bottle 32 oz",
    "Cascade Gear Co.",
    "outdoors",
    3400,
    160,
    46,
    4200,
    "Double-wall bottle that holds ice through a July hike and coffee heat through December.",
    {
      Capacity: "32 oz",
      Insulation: "18/8 stainless double wall",
      ColdHold: "Ice 24+ h",
      Lid: "Interchangeable straw/spout",
    },
    ["bottle", "hydration", "insulated", "hiking", "everyday"],
  ),
  p(
    "cascade-two-burner-camp-stove",
    "Cascade Gear Two-Burner Camp Stove",
    "Cascade Gear Co.",
    "outdoors",
    8900,
    26,
    45,
    760,
    "Two burners, wind baffles, and matchless ignition — base-camp pancakes are back on.",
    {
      Burners: "2 x 10,000 BTU",
      Ignition: "Push-button matchless",
      Simmer: "Independent flame control",
      Weight: "9.7 lb",
    },
    ["camp-stove", "cooking", "camping", "tailgate"],
  ),
  p(
    "ridgeline-stormshell-jacket",
    "Ridgeline StormShell Rain Jacket",
    "Ridgeline Outfitters",
    "outdoors",
    13900,
    45,
    46,
    1533,
    "2.5-layer shell with pit zips that packs into its own chest pocket and forgets it's there.",
    {
      Waterproof: "20k/20k membrane",
      Seams: "Fully taped",
      Vents: "Core pit zips",
      Packed: "Self-storing chest pocket",
    },
    ["rain-jacket", "shell", "hiking", "waterproof", "travel"],
  ),
  p(
    "trailhead-led-headlamp",
    "Trailhead Supply 400 lm Headlamp",
    "Trailhead Supply",
    "outdoors",
    2900,
    140,
    45,
    2410,
    "Rechargeable headlamp with red night mode and a beam that actually reaches the next switchback.",
    {
      Output: "400 lumens max",
      BeamDistance: "110 m",
      Modes: "White high/low, red night vision",
      Battery: "USB-C rechargeable, 12 h low",
    },
    ["headlamp", "camping", "running-at-night", "caving"],
  ),
  p(
    "cascade-45qt-cooler",
    "Cascade Gear 45 qt Cooler",
    "Cascade Gear Co.",
    "outdoors",
    17900,
    0,
    47,
    640,
    "Rotomolded cooler with three-day ice retention and bear-resistant latches.",
    {
      Capacity: "45 qt / 62 cans",
      IceRetention: "3 days",
      Construction: "Rotomolded, 2\" walls",
      Certified: "IGBC bear-resistant",
    },
    ["cooler", "camping", "road-trip", "fishing"],
  ),
  p(
    "trailhead-double-hammock",
    "Trailhead Supply Double Hammock",
    "Trailhead Supply",
    "outdoors",
    4900,
    97,
    46,
    2050,
    "Ripstop nylon hammock rated for two adults, with whoopie slings that weigh less than lunch.",
    {
      Capacity: "450 lb",
      Material: "70D ripstop nylon",
      Suspended: "Tree straps included",
      Packed: "Softball-sized stuff sack",
    },
    ["hammock", "camping", "lounging", "backyard"],
  ),

  /* ── Everyday carry ────────────────────────────────────────────────────── */
  p(
    "pocketforge-slimline-wallet",
    "Pocketforge Slimline RFID Wallet",
    "Pocketforge",
    "everyday-carry",
    3900,
    130,
    46,
    3140,
    "Six-card aluminum wallet thinner than your old one, with a quick-access thumb slide.",
    {
      CardSlots: "6 cards + cash strap",
      Blocking: "RFID shielding",
      Thickness: "8 mm loaded",
      Material: "6061 aluminum, anodized",
    },
    ["wallet", "rfid", "minimalist", "gift"],
  ),
  p(
    "slate-steel-field-pen",
    "Slate & Steel Titanium Field Pen",
    "Slate & Steel",
    "everyday-carry",
    5500,
    62,
    45,
    880,
    "Grade-5 titanium pen that writes upside-down, survives laundry, and feels like a tool.",
    {
      Material: "Grade 5 titanium",
      Refill: "Pressurized all-angle ink",
      Length: '4.7"',
      Weight: "1.1 oz",
    },
    ["pen", "titanium", "gift", "edc"],
  ),
  p(
    "carryon-commuter-backpack-26",
    "Carryon Goods 26 L Commuter Backpack",
    "Carryon Goods",
    "everyday-carry",
    11900,
    48,
    46,
    1720,
    "Weatherproof commuter pack with a clamshell main, luggage pass-through, and honest pockets.",
    {
      Capacity: "26 L",
      Laptop: "Padded 16\" sleeve",
      Fabric: "Recycled 900D, DWR coat",
      Extras: "Luggage pass-through, hidden pocket",
    },
    ["backpack", "commuter", "work", "travel", "laptop"],
    true,
  ),
  p(
    "pocketforge-key-organizer",
    "Pocketforge Smart Key Organizer",
    "Pocketforge",
    "everyday-carry",
    2400,
    155,
    44,
    2410,
    "Swiss-style folder that silences jangling keys into a pocket-flat paddle.",
    {
      KeysHeld: "2–8 keys",
      Tools: "Bottle opener + loop",
      Material: "Anodized aluminum",
    },
    ["keys", "organizer", "minimalist"],
  ),
  p(
    "slate-steel-multitasker-multitool",
    "Slate & Steel Multitasker 12-in-1 Multitool",
    "Slate & Steel",
    "everyday-carry",
    6900,
    71,
    47,
    1360,
    "Needle-nose pliers, scissors, drivers, and a serrated blade in a pocketable frame.",
    {
      Tools: "12 locking tools",
      Steel: "420HC, stonewashed",
      Sheath: "Nylon belt sheath",
      Weight: "7.4 oz",
    },
    ["multitool", "pliers", "gift", "camping"],
  ),
  p(
    "carryon-packable-jacket",
    "Carryon Goods Packable Windbreaker",
    "Carryon Goods",
    "everyday-carry",
    8900,
    59,
    44,
    990,
    "Featherweight windbreaker that zips into its own chest pocket and lives in your bag.",
    {
      Weight: "4.6 oz",
      Packed: "Fits in own pocket",
      Fabric: "Ripstop with DWR finish",
      Fit: "Standard, drawcord hem",
    },
    ["jacket", "windbreaker", "packable", "travel"],
  ),
  p(
    "slate-steel-a5-notebook",
    "Slate & Steel A5 Dotted Notebook",
    "Slate & Steel",
    "everyday-carry",
    1800,
    200,
    46,
    3050,
    "120 gsm dot-grid pages that laugh at fountain pens, in a lay-flat binding.",
    {
      Pages: "192 dotted, 120 gsm",
      Binding: "Lay-flat sewn",
      Cover: "Hardcover, elastic + ribbon",
    },
    ["notebook", "journaling", "writing"],
  ),
  p(
    "carryon-travel-umbrella",
    "Carryon Goods Travel Umbrella",
    "Carryon Goods",
    "everyday-carry",
    3200,
    111,
    45,
    1470,
    "Nine-rib fiberglass umbrella rated for gusts, small enough to forget until needed.",
    {
      Canopy: "42\", Teflon-coated",
      Ribs: "9 fiberglass, wind-tested 45 mph",
      AutoOpenClose: "One-button",
      Weight: "11 oz",
    },
    ["umbrella", "rain", "travel", "compact"],
  ),
];

/** Curated collections surfaced on the home page. */
export const COLLECTIONS: Array<{
  slug: string;
  title: string;
  description: string;
  tag: string;
}> = [
  {
    slug: "desk-upgrades",
    title: "Desk Upgrades",
    description: "Monitors, keyboards, and the little things that make 9 a.m. better.",
    tag: "desk-setup",
  },
  {
    slug: "home-gym-starters",
    title: "Home Gym Starters",
    description: "Strength gear that fits a spare corner and a real budget.",
    tag: "home-gym",
  },
  {
    slug: "commute-kit",
    title: "The Commute Kit",
    description: "Noise cancelling, power banks, and bags built for the daily grind.",
    tag: "commuting",
  },
  {
    slug: "coffee-corner",
    title: "Coffee Corner",
    description: "Pour-over kettles, burr grinders, and scales for better mornings.",
    tag: "coffee",
  },
];
